/**
 * seed.ts — populate LoopCode with 40 curated problems (5 per pattern) and a
 * simulated ~3-week study history, so the dashboard, mastery map, and streak
 * counter all have realistic data the moment you first open the app.
 *
 * The history is generated by running the REAL SM-2 scheduler day by day, so the
 * seeded intervals/ease factors are internally consistent with the algorithm.
 * A seeded PRNG keeps the result reproducible.
 *
 * Run with:  npm run db:seed
 */

import { PrismaClient } from "@prisma/client";
import { simulateStudyHistory } from "../src/lib/studyHistory.js";

const prisma = new PrismaClient();

interface SeedProblem {
  title: string;
  url: string;
  pattern: string;
  difficulty: "easy" | "medium" | "hard";
}

// 5 well-known problems per pattern — the classic NeetCode/LeetCode set.
const PROBLEMS: SeedProblem[] = [
  // ── Two Pointers ──────────────────────────────────────────────────────────
  { title: "Valid Palindrome", url: "https://leetcode.com/problems/valid-palindrome/", pattern: "Two Pointers", difficulty: "easy" },
  { title: "Two Sum II - Input Array Is Sorted", url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", pattern: "Two Pointers", difficulty: "medium" },
  { title: "3Sum", url: "https://leetcode.com/problems/3sum/", pattern: "Two Pointers", difficulty: "medium" },
  { title: "Container With Most Water", url: "https://leetcode.com/problems/container-with-most-water/", pattern: "Two Pointers", difficulty: "medium" },
  { title: "Trapping Rain Water", url: "https://leetcode.com/problems/trapping-rain-water/", pattern: "Two Pointers", difficulty: "hard" },

  // ── Sliding Window ────────────────────────────────────────────────────────
  { title: "Best Time to Buy and Sell Stock", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", pattern: "Sliding Window", difficulty: "easy" },
  { title: "Longest Substring Without Repeating Characters", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", pattern: "Sliding Window", difficulty: "medium" },
  { title: "Longest Repeating Character Replacement", url: "https://leetcode.com/problems/longest-repeating-character-replacement/", pattern: "Sliding Window", difficulty: "medium" },
  { title: "Permutation in String", url: "https://leetcode.com/problems/permutation-in-string/", pattern: "Sliding Window", difficulty: "medium" },
  { title: "Minimum Window Substring", url: "https://leetcode.com/problems/minimum-window-substring/", pattern: "Sliding Window", difficulty: "hard" },

  // ── Binary Search ─────────────────────────────────────────────────────────
  { title: "Binary Search", url: "https://leetcode.com/problems/binary-search/", pattern: "Binary Search", difficulty: "easy" },
  { title: "Search a 2D Matrix", url: "https://leetcode.com/problems/search-a-2d-matrix/", pattern: "Binary Search", difficulty: "medium" },
  { title: "Koko Eating Bananas", url: "https://leetcode.com/problems/koko-eating-bananas/", pattern: "Binary Search", difficulty: "medium" },
  { title: "Find Minimum in Rotated Sorted Array", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", pattern: "Binary Search", difficulty: "medium" },
  { title: "Median of Two Sorted Arrays", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", pattern: "Binary Search", difficulty: "hard" },

  // ── DFS/BFS (trees) ───────────────────────────────────────────────────────
  { title: "Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree/", pattern: "DFS/BFS", difficulty: "easy" },
  { title: "Maximum Depth of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", pattern: "DFS/BFS", difficulty: "easy" },
  { title: "Binary Tree Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", pattern: "DFS/BFS", difficulty: "medium" },
  { title: "Validate Binary Search Tree", url: "https://leetcode.com/problems/validate-binary-search-tree/", pattern: "DFS/BFS", difficulty: "medium" },
  { title: "Binary Tree Maximum Path Sum", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", pattern: "DFS/BFS", difficulty: "hard" },

  // ── Graphs ────────────────────────────────────────────────────────────────
  { title: "Number of Islands", url: "https://leetcode.com/problems/number-of-islands/", pattern: "Graphs", difficulty: "medium" },
  { title: "Clone Graph", url: "https://leetcode.com/problems/clone-graph/", pattern: "Graphs", difficulty: "medium" },
  { title: "Course Schedule", url: "https://leetcode.com/problems/course-schedule/", pattern: "Graphs", difficulty: "medium" },
  { title: "Pacific Atlantic Water Flow", url: "https://leetcode.com/problems/pacific-atlantic-water-flow/", pattern: "Graphs", difficulty: "medium" },
  { title: "Word Ladder", url: "https://leetcode.com/problems/word-ladder/", pattern: "Graphs", difficulty: "hard" },

  // ── Dynamic Programming ───────────────────────────────────────────────────
  { title: "Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", pattern: "Dynamic Programming", difficulty: "easy" },
  { title: "House Robber", url: "https://leetcode.com/problems/house-robber/", pattern: "Dynamic Programming", difficulty: "medium" },
  { title: "Coin Change", url: "https://leetcode.com/problems/coin-change/", pattern: "Dynamic Programming", difficulty: "medium" },
  { title: "Longest Increasing Subsequence", url: "https://leetcode.com/problems/longest-increasing-subsequence/", pattern: "Dynamic Programming", difficulty: "medium" },
  { title: "Edit Distance", url: "https://leetcode.com/problems/edit-distance/", pattern: "Dynamic Programming", difficulty: "hard" },

  // ── Heaps ─────────────────────────────────────────────────────────────────
  { title: "Kth Largest Element in a Stream", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/", pattern: "Heaps", difficulty: "easy" },
  { title: "Last Stone Weight", url: "https://leetcode.com/problems/last-stone-weight/", pattern: "Heaps", difficulty: "easy" },
  { title: "K Closest Points to Origin", url: "https://leetcode.com/problems/k-closest-points-to-origin/", pattern: "Heaps", difficulty: "medium" },
  { title: "Task Scheduler", url: "https://leetcode.com/problems/task-scheduler/", pattern: "Heaps", difficulty: "medium" },
  { title: "Find Median from Data Stream", url: "https://leetcode.com/problems/find-median-from-data-stream/", pattern: "Heaps", difficulty: "hard" },

  // ── Backtracking ──────────────────────────────────────────────────────────
  { title: "Subsets", url: "https://leetcode.com/problems/subsets/", pattern: "Backtracking", difficulty: "medium" },
  { title: "Combination Sum", url: "https://leetcode.com/problems/combination-sum/", pattern: "Backtracking", difficulty: "medium" },
  { title: "Permutations", url: "https://leetcode.com/problems/permutations/", pattern: "Backtracking", difficulty: "medium" },
  { title: "Word Search", url: "https://leetcode.com/problems/word-search/", pattern: "Backtracking", difficulty: "medium" },
  { title: "N-Queens", url: "https://leetcode.com/problems/n-queens/", pattern: "Backtracking", difficulty: "hard" },
];

async function main() {
  console.log("[seed] Resetting database…");
  await prisma.reviewLog.deleteMany();
  await prisma.userProgress.deleteMany();
  await prisma.problem.deleteMany();

  console.log(`[seed] Inserting ${PROBLEMS.length} problems…`);
  const created = [];
  for (const p of PROBLEMS) {
    const problem = await prisma.problem.create({ data: p });
    created.push(problem);
  }

  // Generate a reproducible ~3-week history with the real SM-2 scheduler
  // (see src/lib/studyHistory.ts — this logic is unit-tested).
  console.log("[seed] Simulating study history…");
  const { reviews, progress } = simulateStudyHistory(created.length, {
    today: new Date(),
    seed: 20260915,
  });

  console.log(`[seed] Writing ${reviews.length} review logs…`);
  for (const log of reviews) {
    await prisma.reviewLog.create({
      data: {
        problemId: created[log.problemIndex].id,
        rating: log.rating,
        quality: log.quality,
        intervalDays: log.intervalDays,
        easeFactor: log.easeFactor,
        xp: log.xp,
        reviewedAt: log.reviewedAt,
      },
    });
  }

  console.log("[seed] Writing final progress for each problem…");
  for (const prog of progress) {
    await prisma.userProgress.create({
      data: {
        problemId: created[prog.problemIndex].id,
        repetitions: prog.repetitions,
        easeFactor: prog.easeFactor,
        intervalDays: prog.intervalDays,
        nextReviewDate: prog.nextReviewDate,
        lastReviewedAt: prog.lastReviewedAt,
      },
    });
  }

  const now = new Date();
  const dueToday = progress.filter((p) => p.nextReviewDate <= now).length;
  console.log(
    `[seed] Done. ${PROBLEMS.length} problems, ${reviews.length} reviews, ~${dueToday} due today.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
